from PyQt5 import QtGui, QtCore
from PyQt5.QtGui import QFont, QBrush, QColor


def getPalette():
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
    brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
    gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
    gradient.setSpread(QtGui.QGradient.PadSpread)
    gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
    gradient.setColorAt(0.298507, QtGui.QColor(83, 97, 142))
    gradient.setColorAt(1.0, QtGui.QColor(97, 69, 128))
    brush = QtGui.QBrush(gradient)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
    return palette

def getPricePalette():
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
    brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
    brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
    brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
    return palette